#!/bin/bash

# Count all .cpp and .h files under src/
find src/ -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.c" \) \
    -exec wc -l {} + \
    | awk 'END {print "Total lines:", $1}'